version: '3'
services:
  postgres-db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=django_dev
    ports:
      - '5432:5432'
  redis:
    image: redis
    restart: always
    container_name: 'mymp_redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    container_name: 'mymp'
    command: >
      sh -c "python3 manage.py migrate&&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - postgres-db

  celery:
    build: .
    container_name: 'mymp_celery'
    command: celery -A mymp worker -B -E
    volumes:
      - .:/usr/src/app
    links:
      - redis
    depends_on:
      - web
      - redis
      - postgres-db
volumes:
  postgres_data: